LISTA_DIAS = ['Segunda', 'Terca', 'Quarta', 'Quinta', 'Sexta']

LISTA_HORARIOS = ['18:30h - 20:10h', '20:10h - 21:50h']

QUANT_DE_DIAS = len(LISTA_DIAS)

QUANT_DE_HORARIOS = len(LISTA_HORARIOS)

QUANT_DE_PERIODOS = 9

QUANT_DA_POPULACAO_INICIAL = 2

QUANT_HORARIOS_DISPO = 10

QUANT_MUTACOES = 3