LISTA_DIAS = ['Segunda', 'Terca', 'Quarta', 'Quinta', 'Sexta']

LISTA_HORARIOS = ['18:30h - 20:10h', '20:10h - 21:50h']

QUANT_DE_DIAS = len(LISTA_DIAS)

QUANT_DE_HORARIOS = len(LISTA_HORARIOS)

QUANT_DE_PERIODOS = 9

QUANT_DA_POPULACAO_INICIAL = 70

QUANT_HORARIOS_DISPO = 10

QUANT_MUTACOES = 5

QUANT_GERACOES_SEM_MELHORIA = 250

MELHOR_APTIDAO = 0

PONTUACAO_CHOQUE = 10000

PONTUACAO_DIA_NAO_LECIONAVEL = 10

PONTUACAO_AULAS_CONCENTRADAS = 2